name: 'cabal-install tests'
description: ''
inputs:
  ghc-exe:
    description: 'GHC version to use'
    required: true
#  cabal-version:
#    description: 'cabal-install version to use'
#    required: false
#    default: 'latest'
#outputs:
#  random-number: 
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: ${{ inputs.ghc-exe }} --version
      shell: bash
